### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by Khazella** [Icehunter/AutoTranslateXIV#2]
Is there any tutorials to get the Google Service Key and others?

**Comment by Icehunter** [comment]
I'm going to translate this into a readme but you can find info on it here:

https://neliosoftware.com/blog/how-to-generate-an-api-key-for-google-translate/

https://docs.microsoft.com/en-us/azure/cognitive-services/translator/how-to-create-translator-resource

I have a pay-as-you-go subscription in Azure and created my cognitive resource. Even being on a Japanese server I never go over the character limit.

Google is used in much the same way.

**Comment by Khazella** [comment]
I try the made the azure too put the key and region but it doesn't work
